// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIoyPykXrNF1mSAo5kwOYWqxeOSKljnQ4',
    appId: '1:786350720475:web:5e6012ef6cc6e63d9b13fe',
    messagingSenderId: '786350720475',
    projectId: 'demo012-8cdb6',
    authDomain: 'demo012-8cdb6.firebaseapp.com',
    storageBucket: 'demo012-8cdb6.firebasestorage.app',
    measurementId: 'G-MFV7ZPVD10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-UdmrwFoQ26dHh0tOxoLyuUNoWlywm8U',
    appId: '1:786350720475:android:1989af52d02767919b13fe',
    messagingSenderId: '786350720475',
    projectId: 'demo012-8cdb6',
    storageBucket: 'demo012-8cdb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk1wMh1C4IFcQM3oVjX6rTl6zeTD0RMb4',
    appId: '1:786350720475:ios:7f587423afaa35619b13fe',
    messagingSenderId: '786350720475',
    projectId: 'demo012-8cdb6',
    storageBucket: 'demo012-8cdb6.firebasestorage.app',
    iosBundleId: 'com.example.flutterTutorials',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk1wMh1C4IFcQM3oVjX6rTl6zeTD0RMb4',
    appId: '1:786350720475:ios:7f587423afaa35619b13fe',
    messagingSenderId: '786350720475',
    projectId: 'demo012-8cdb6',
    storageBucket: 'demo012-8cdb6.firebasestorage.app',
    iosBundleId: 'com.example.flutterTutorials',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIoyPykXrNF1mSAo5kwOYWqxeOSKljnQ4',
    appId: '1:786350720475:web:9c9ad0f7328477249b13fe',
    messagingSenderId: '786350720475',
    projectId: 'demo012-8cdb6',
    authDomain: 'demo012-8cdb6.firebaseapp.com',
    storageBucket: 'demo012-8cdb6.firebasestorage.app',
    measurementId: 'G-PK9T3M1KW5',
  );
}
